export type UserData = Partial<{
  submitPlace: string;
  submitAuthority: string;
  surname: string;
  previousSurname: string;
  familyName: string;
  name: string;
  previousName: string;
  fatherName: string;
  motherName: string;
  motherMaidenName: string;
  birthday: string;
  sex: string;
  placeOfBirth: string;
  countryOfBirth: string;
  nationality: string;
  citizenship: string;
  martialStatus: string;
  colourOfEyes: string;
  specialMarks: string;
  pesel: string;
}>;
