import { Visit } from '@/UserDataForm/components/SteppedContent/components/PreviousVisits/components/PreviousPolandVisits/PreviousPolandVisits';
import { Travel } from '@/UserDataForm/components/SteppedContent/components/PreviousVisits/components/TravelsOutsidePoland/TravelsOutsidePoland';

export type UserData = Partial<{
  submitDate: string;
  submitPlace: string;
  submitAuthority: string;
  surname: string;
  previousSurname: string;
  familyName: string;
  name: string;
  previousName: string;
  fatherName: string;
  motherName: string;
  motherMaidenName: string;
  birthday: string;
  sex: string;
  placeOfBirth: string;
  countryOfBirth: string;
  nationality: string;
  citizenship: string;
  martialStatus: string;
  education: string;
  height: string;
  colourOfEyes: string;
  specialMarks: string;
  pesel: string;
  email: string;
  phone: string;
  cprVoivodship: string;
  cprCity: string;
  cprStreet: string;
  cprHouseNumber: string;
  cprApartmentNumber: string;
  cprPostalCode: string;
  stayPurpose: string;
  stayPurposeAdditional: string;
  familyMemebers: FamilyMember[];
  isCurrentlyInPoland: string;
  lastEntryIntoPoland: string;
  legalBasisForStaying: string;
  previousVisitsPoland: Visit[];
  travelsOutsidePoland: Travel[];
  meansOfSubstence: string;
  medicalInsurance: string;
  clauseDLRS: string;
  isSentenced: string;
  sentencedDescription: string;
  isSubjectOfCriminal: string;
  subjectOfCriminalDescription: string;
  hasLiabilitiesResulting: string;
  liabilitiesResultingDescription: string;
  attachmentsList: string[];
}>;

export type FamilyMember = {
  id: string;
  name: string;
  sex: string;
  birthday: string;
  kinship: string;
  citizenship: string;
  residencePlace: string;
  isApplying: string;
  isDependent: string;
};
