type CellMeta = {
  shortName: string;
  cellsAmount: number;
  type?: 'select' | 'date';
  indexShift?: number;
};

export const dataMapWithMeta: Record<string, CellMeta> = {
  submitDate: { shortName: '', cellsAmount: 0, type: 'date' },
  submitPlace: { shortName: '', cellsAmount: 1 },
  submitAuthority: { shortName: '', cellsAmount: 1 },
  surname: { shortName: 'A.S', cellsAmount: 20 },
  previousSurname: { shortName: '', cellsAmount: 40 },
  familyName: { shortName: 'A.SF', cellsAmount: 20 },
  name: { shortName: 'A.N', cellsAmount: 20 },
  previousName: { shortName: '', cellsAmount: 40 },
  fatherName: { shortName: '', cellsAmount: 20 },
  motherName: { shortName: '', cellsAmount: 20 },
  motherMaidenName: { shortName: '', cellsAmount: 20 },
  birthdayDate: { shortName: '', cellsAmount: 0, type: 'date' },
  sex: { shortName: '', cellsAmount: 1 },
  placeOfBirth: { shortName: '', cellsAmount: 20 },
  countryOfBirth: { shortName: '', cellsAmount: 20 },
  nationality: { shortName: '', cellsAmount: 20 },
  citizenship: { shortName: '', cellsAmount: 20 },
  martialStatus: { shortName: '', cellsAmount: 20 },
  education: { shortName: '', cellsAmount: 20 },
  height: { shortName: '', cellsAmount: 3 },
  colourOfEyes: { shortName: '', cellsAmount: 20 },
  specialMarks: { shortName: '', cellsAmount: 20 },
  pesel: { shortName: '', cellsAmount: 11 },
  phone: { shortName: '', cellsAmount: 20 },
  email: { shortName: '', cellsAmount: 20 },
  isFamilyMemberOutsidePoland: { shortName: '', cellsAmount: 1 },
  cprVoivodship: { shortName: '', cellsAmount: 20 },
  cprCity: { shortName: '', cellsAmount: 20 },
  cprStreet: { shortName: '', cellsAmount: 20 },
  cprHouseNumber: { shortName: '', cellsAmount: 7 },
  cprApartmentNumber: { shortName: '', cellsAmount: 7 },
  cprPostalCode: { shortName: '', cellsAmount: 6 },
  stayPurpose: { shortName: '', cellsAmount: 16, type: 'select' },
  stayPurposeAdditional: { shortName: '', cellsAmount: 1 },

  familyMemberNameAndSurname_1: { shortName: '', cellsAmount: 1 },
  familyMemberSex_1: { shortName: '', cellsAmount: 1 },
  familyMemberBirthday_1: { shortName: '', cellsAmount: 1 },
  familyMemberKinDegree_1: { shortName: '', cellsAmount: 1 },
  familyMemberCitizenShip_1: { shortName: '', cellsAmount: 1 },
  familyMemberResidence_1: { shortName: '', cellsAmount: 1 },
  familyMemberIsApplyingTP_1: { shortName: '', cellsAmount: 1 },
  familyMemberIsDependent_1: { shortName: '', cellsAmount: 1 },

  familyMemberNameAndSurname_2: { shortName: '', cellsAmount: 1 },
  familyMemberSex_2: { shortName: '', cellsAmount: 1 },
  familyMemberBirthday_2: { shortName: '', cellsAmount: 1 },
  familyMemberKinDegree_2: { shortName: '', cellsAmount: 1 },
  familyMemberCitizenShip_2: { shortName: '', cellsAmount: 1 },
  familyMemberResidence_2: { shortName: '', cellsAmount: 1 },
  familyMemberIsApplyingTP_2: { shortName: '', cellsAmount: 1 },
  familyMemberIsDependent_2: { shortName: '', cellsAmount: 1 },

  familyMemberNameAndSurname_3: { shortName: '', cellsAmount: 1 },
  familyMemberSex_3: { shortName: '', cellsAmount: 1 },
  familyMemberBirthday_3: { shortName: '', cellsAmount: 1 },
  familyMemberKinDegree_3: { shortName: '', cellsAmount: 1 },
  familyMemberCitizenShip_3: { shortName: '', cellsAmount: 1 },
  familyMemberResidence_3: { shortName: '', cellsAmount: 1 },
  familyMemberIsApplyingTP_3: { shortName: '', cellsAmount: 1 },
  familyMemberIsDependent_3: { shortName: '', cellsAmount: 1 },

  familyMemberNameAndSurname_4: { shortName: '', cellsAmount: 1 },
  familyMemberSex_4: { shortName: '', cellsAmount: 1 },
  familyMemberBirthday_4: { shortName: '', cellsAmount: 1 },
  familyMemberKinDegree_4: { shortName: '', cellsAmount: 1 },
  familyMemberCitizenShip_4: { shortName: '', cellsAmount: 1 },
  familyMemberResidence_4: { shortName: '', cellsAmount: 1 },
  familyMemberIsApplyingTP_4: { shortName: '', cellsAmount: 1 },
  familyMemberIsDependent_4: { shortName: '', cellsAmount: 1 },

  familyMemberNameAndSurname_5: { shortName: '', cellsAmount: 1 },
  familyMemberSex_5: { shortName: '', cellsAmount: 1 },
  familyMemberBirthday_5: { shortName: '', cellsAmount: 1 },
  familyMemberKinDegree_5: { shortName: '', cellsAmount: 1 },
  familyMemberCitizenShip_5: { shortName: '', cellsAmount: 1 },
  familyMemberResidence_5: { shortName: '', cellsAmount: 1 },
  familyMemberIsApplyingTP_5: { shortName: '', cellsAmount: 1 },
  familyMemberIsDependent_5: { shortName: '', cellsAmount: 1 },

  previousVisitsPoland: { shortName: '', cellsAmount: 1 },
  isCurrentlyInPoland: { shortName: '', cellsAmount: 2, type: 'select' },
  lastEntryIntoPolandDate: { shortName: '', cellsAmount: 0, type: 'date' },
  legalBasisForStaying: { shortName: '', cellsAmount: 4, type: 'select' },
  travelsOutsidePoland: { shortName: '', cellsAmount: 1 },
  meansOfSubstence: { shortName: '', cellsAmount: 1 },
  medicalInsurance: { shortName: '', cellsAmount: 1 },
  clauseDLRS: { shortName: '', cellsAmount: 1 },
  isSentenced: { shortName: '', cellsAmount: 2, type: 'select' },
  sentencedDescription: { shortName: '', cellsAmount: 1 },
  isSubjectOfCriminal: { shortName: '', cellsAmount: 2, type: 'select' },
  subjectOfCriminalDescription: { shortName: '', cellsAmount: 1 },
  hasLiabilitiesResulting: { shortName: '', cellsAmount: 2, type: 'select' },
  liabilitiesResultingDescription: { shortName: '', cellsAmount: 1 },

  attachment_1: { shortName: '', cellsAmount: 1 },
  attachment_2: { shortName: '', cellsAmount: 1 },
  attachment_3: { shortName: '', cellsAmount: 1 },
  attachment_4: { shortName: '', cellsAmount: 1 },
  attachment_5: { shortName: '', cellsAmount: 1 },
  attachment_6: { shortName: '', cellsAmount: 1 },
  attachment_7: { shortName: '', cellsAmount: 1 },
  attachment_8: { shortName: '', cellsAmount: 1 },
  attachment_9: { shortName: '', cellsAmount: 1 },
  attachment_10: { shortName: '', cellsAmount: 1 },
  attachment_11: { shortName: '', cellsAmount: 1 },
  attachment_12: { shortName: '', cellsAmount: 1 },
  attachment_13: { shortName: '', cellsAmount: 1 },
  attachment_14: { shortName: '', cellsAmount: 1 },
  attachment_15: { shortName: '', cellsAmount: 1 },
};
