type CellMeta = {
  shortName: string;
  cellsAmount: number;
  type?: "select" | "date";
  indexShift?: number;
};

export const dataMapWithMeta: Record<string, CellMeta> = {
  // ["submittion-Date"]: { shortName: "", cellsAmount: 1, type: "date" },
  submitDate: { shortName: "", cellsAmount: 0, type: "date" },
  submitPlace: { shortName: "", cellsAmount: 1 },
  submitAuthority: { shortName: "", cellsAmount: 1 },
  surname: { shortName: "A.S", cellsAmount: 20 },
  previousSurname: { shortName: "", cellsAmount: 40 },
  familyName: { shortName: "A.SF", cellsAmount: 20 },
  name: { shortName: "A.N", cellsAmount: 20 },
  previousName: { shortName: "", cellsAmount: 40 },
  fatherName: { shortName: "", cellsAmount: 20 },
  motherName: { shortName: "", cellsAmount: 20 },
  motherMaidenName: { shortName: "", cellsAmount: 20 },
  birthdayYear: { shortName: "", cellsAmount: 4 },
  birthdayMonth: { shortName: "", cellsAmount: 2 },
  birthdayDay: { shortName: "", cellsAmount: 2 },
  sex: { shortName: "", cellsAmount: 1 },
  placeOfBirth: { shortName: "", cellsAmount: 20 },
  countryOfBirth: { shortName: "", cellsAmount: 20 },
  nationality: { shortName: "", cellsAmount: 20 },
  citizenship: { shortName: "", cellsAmount: 20 },
  martialStatus: { shortName: "", cellsAmount: 20 },
  education: { shortName: "", cellsAmount: 20 },
  heigh: { shortName: "", cellsAmount: 3 },
  colourOfEyes: { shortName: "", cellsAmount: 20 },
  specialMarks: { shortName: "", cellsAmount: 20 },
  pesel: { shortName: "", cellsAmount: 11 },
  phone: { shortName: "", cellsAmount: 20 },
  email: { shortName: "", cellsAmount: 20 },
  isFamilyMemberOutsidePoland: { shortName: "", cellsAmount: 1 },
  cprVoivodship: { shortName: "", cellsAmount: 20 },
  cprCity: { shortName: "", cellsAmount: 20 },
  cprStreet: { shortName: "", cellsAmount: 20 },
  cprHouseNumber: { shortName: "", cellsAmount: 7 },
  cprApartmentNumber: { shortName: "", cellsAmount: 7 },
  cprPostalCode: { shortName: "", cellsAmount: 6 },
  stayPurpose: { shortName: "", cellsAmount: 16, type: "select" },
  stayPurposeAdditional: { shortName: "", cellsAmount: 1 },
  familyMemberNameAndSurname_1: { shortName: "", cellsAmount: 1 },
  familyMemberSex_1: { shortName: "", cellsAmount: 1 },
  familyMemberBirthday_1: { shortName: "", cellsAmount: 1 },
  familyMemberKinDegree_1: { shortName: "", cellsAmount: 1 },
  familyMemberCitizenShip_1: { shortName: "", cellsAmount: 1 },
  familyMemberResidence_1: { shortName: "", cellsAmount: 1 },
  familyMemberIsApplyingTP_1: { shortName: "", cellsAmount: 1 },
  familyMemberIsDependent_1: { shortName: "", cellsAmount: 1 },

  previousVisitsPoland: { shortName: "", cellsAmount: 1 },
  isCurrentlyInPoland: { shortName: "", cellsAmount: 2, type: "select" },
  lastEntryIntoPolandYear: { shortName: "", cellsAmount: 4 },
  lastEntryIntoPolandMonth: { shortName: "", cellsAmount: 2 },
  lastEntryIntoPolandDay: { shortName: "", cellsAmount: 2 },
  legalBasisForStaying: { shortName: "", cellsAmount: 4, type: "select" },
  travelsOutsidePoland: { shortName: "", cellsAmount: 1 },
  meansOfSubstence: { shortName: "", cellsAmount: 1 },
  medicalInsurance: { shortName: "", cellsAmount: 1 },
  clauseDLRS: { shortName: "", cellsAmount: 1 },
  isSentenced: { shortName: "", cellsAmount: 2, type: "select" },
  sentencedDescription: { shortName: "", cellsAmount: 1 },
  isSubjectOfCriminal: { shortName: "", cellsAmount: 2, type: "select" },
  subjectOfCriminalDescription: { shortName: "", cellsAmount: 1 },
  hasLiabilitiesResulting: { shortName: "", cellsAmount: 2, type: "select" },
  liabilitiesResultingDescription: { shortName: "", cellsAmount: 1 },
};
